import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";

interface CaseStudyData {
  title: string;
  description: string;
  industry: string;
  stat: string;
  statLabel: string;
  metrics: { label: string; value: string }[];
}

interface TemplateData {
  templateType: string;
  content: string;
}

// PDF Export for Case Study
export const exportCaseStudyToPDF = (caseStudy: CaseStudyData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(caseStudy.title, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 10 + 10;

  // Industry Tag
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`INDUSTRY: ${caseStudy.industry.toUpperCase()}`, margin, y);
  y += 15;

  // Primary Stat
  doc.setTextColor(34, 139, 34); // Green color
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.text(caseStudy.stat, margin, y);
  y += 12;
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0);
  doc.text(caseStudy.statLabel, margin, y);
  y += 20;

  // Description
  doc.setFontSize(11);
  const descLines = doc.splitTextToSize(caseStudy.description, contentWidth);
  doc.text(descLines, margin, y);
  y += descLines.length * 6 + 15;

  // Metrics
  if (caseStudy.metrics.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Key Metrics", margin, y);
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    caseStudy.metrics.forEach((metric) => {
      doc.text(`• ${metric.label}: ${metric.value}`, margin + 5, y);
      y += 7;
    });
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Rhosonics Brand Tools", margin, y);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin - 30, y);

  doc.save(`case-study-${caseStudy.industry}.pdf`);
};

// Word Export for Case Study
export const exportCaseStudyToWord = async (caseStudy: CaseStudyData) => {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: caseStudy.title,
                bold: true,
                size: 40,
              }),
            ],
            heading: HeadingLevel.TITLE,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `INDUSTRY: ${caseStudy.industry.toUpperCase()}`,
                size: 20,
                color: "666666",
              }),
            ],
            spacing: { before: 200, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: caseStudy.stat,
                bold: true,
                size: 72,
                color: "228B22",
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: caseStudy.statLabel,
                size: 24,
              }),
            ],
            spacing: { after: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: caseStudy.description,
                size: 22,
              }),
            ],
            spacing: { after: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Key Metrics",
                bold: true,
                size: 28,
              }),
            ],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 200 },
          }),
          ...caseStudy.metrics.map(
            (metric) =>
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${metric.label}: `,
                    bold: true,
                    size: 22,
                  }),
                  new TextRun({
                    text: metric.value,
                    size: 22,
                  }),
                ],
                spacing: { after: 100 },
              })
          ),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Rhosonics Brand Tools • ${new Date().toLocaleDateString()}`,
                size: 16,
                color: "999999",
              }),
            ],
            spacing: { before: 600 },
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `case-study-${caseStudy.industry}.docx`);
};

// PDF Export for Template
export const exportTemplateToPDF = (data: TemplateData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(formatTemplateType(data.templateType), margin, y);
  y += 15;

  // Content
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(data.content, contentWidth);
  
  lines.forEach((line: string) => {
    if (y > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 6;
  });

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Rhosonics Brand Tools", margin, y);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin - 30, y);

  doc.save(`${data.templateType}-template.pdf`);
};

// Word Export for Template
export const exportTemplateToWord = async (data: TemplateData) => {
  const paragraphs = data.content.split("\n").filter(Boolean).map(
    (line) =>
      new Paragraph({
        children: [
          new TextRun({
            text: line,
            size: 22,
          }),
        ],
        spacing: { after: 200 },
      })
  );

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: formatTemplateType(data.templateType),
                bold: true,
                size: 32,
              }),
            ],
            heading: HeadingLevel.TITLE,
            spacing: { after: 400 },
          }),
          ...paragraphs,
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Rhosonics Brand Tools • ${new Date().toLocaleDateString()}`,
                size: 16,
                color: "999999",
              }),
            ],
            spacing: { before: 600 },
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${data.templateType}-template.docx`);
};

function formatTemplateType(type: string): string {
  const labels: Record<string, string> = {
    datasheet: "Product Datasheet",
    specification: "Technical Specification",
    sales_email: "Sales Email",
    support: "Support Response",
    linkedin: "LinkedIn Post",
    press_release: "Press Release",
  };
  return labels[type] || type;
}
