/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrandRouteImport } from './routes/_brand'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LogoAssetsRouteImport } from './routes/logo-assets'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PositioningRouteImport } from './routes/positioning'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SketchesRouteImport } from './routes/sketches'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as VisualSystemRouteImport } from './routes/visual-system'
import { Route as BrandIndexRouteImport } from './routes/_brand.index'
import { Route as BrandApplicationsRouteImport } from './routes/_brand.applications'
import { Route as BrandColorRouteImport } from './routes/_brand.color'
import { Route as BrandDataVizRouteImport } from './routes/_brand.data-viz'
import { Route as BrandIconographyRouteImport } from './routes/_brand.iconography'
import { Route as BrandImageryRouteImport } from './routes/_brand.imagery'
import { Route as BrandLogoRouteImport } from './routes/_brand.logo'
import { Route as BrandPositionRouteImport } from './routes/_brand.position'
import { Route as BrandProofRouteImport } from './routes/_brand.proof'
import { Route as BrandResourcesRouteImport } from './routes/_brand.resources'
import { Route as BrandToolsRouteImport } from './routes/_brand.tools'
import { Route as BrandTypographyRouteImport } from './routes/_brand.typography'
import { Route as BrandVoiceRouteImport } from './routes/_brand.voice'

const BrandRoute = BrandRouteImport.update({
  id: '/_brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoAssetsRoute = LogoAssetsRouteImport.update({
  id: '/logo-assets',
  path: '/logo-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PositioningRoute = PositioningRouteImport.update({
  id: '/positioning',
  path: '/positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchesRoute = SketchesRouteImport.update({
  id: '/sketches',
  path: '/sketches',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualSystemRoute = VisualSystemRouteImport.update({
  id: '/visual-system',
  path: '/visual-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const BrandApplicationsRoute = BrandApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => BrandRoute,
} as any)
const BrandColorRoute = BrandColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => BrandRoute,
} as any)
const BrandDataVizRoute = BrandDataVizRouteImport.update({
  id: '/data-viz',
  path: '/data-viz',
  getParentRoute: () => BrandRoute,
} as any)
const BrandIconographyRoute = BrandIconographyRouteImport.update({
  id: '/iconography',
  path: '/iconography',
  getParentRoute: () => BrandRoute,
} as any)
const BrandImageryRoute = BrandImageryRouteImport.update({
  id: '/imagery',
  path: '/imagery',
  getParentRoute: () => BrandRoute,
} as any)
const BrandLogoRoute = BrandLogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => BrandRoute,
} as any)
const BrandPositionRoute = BrandPositionRouteImport.update({
  id: '/position',
  path: '/position',
  getParentRoute: () => BrandRoute,
} as any)
const BrandProofRoute = BrandProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => BrandRoute,
} as any)
const BrandResourcesRoute = BrandResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => BrandRoute,
} as any)
const BrandToolsRoute = BrandToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => BrandRoute,
} as any)
const BrandTypographyRoute = BrandTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => BrandRoute,
} as any)
const BrandVoiceRoute = BrandVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => BrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BrandIndexRoute
  '/about': typeof AboutRoute
  '/logo-assets': typeof LogoAssetsRoute
  '/newsletter': typeof NewsletterRoute
  '/positioning': typeof PositioningRoute
  '/principles': typeof PrinciplesRoute
  '/review': typeof ReviewRoute
  '/sketches': typeof SketchesRoute
  '/social-media': typeof SocialMediaRoute
  '/visual-system': typeof VisualSystemRoute
  '/applications': typeof BrandApplicationsRoute
  '/color': typeof BrandColorRoute
  '/data-viz': typeof BrandDataVizRoute
  '/iconography': typeof BrandIconographyRoute
  '/imagery': typeof BrandImageryRoute
  '/logo': typeof BrandLogoRoute
  '/position': typeof BrandPositionRoute
  '/proof': typeof BrandProofRoute
  '/resources': typeof BrandResourcesRoute
  '/tools': typeof BrandToolsRoute
  '/typography': typeof BrandTypographyRoute
  '/voice': typeof BrandVoiceRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/logo-assets': typeof LogoAssetsRoute
  '/newsletter': typeof NewsletterRoute
  '/positioning': typeof PositioningRoute
  '/principles': typeof PrinciplesRoute
  '/review': typeof ReviewRoute
  '/sketches': typeof SketchesRoute
  '/social-media': typeof SocialMediaRoute
  '/visual-system': typeof VisualSystemRoute
  '/applications': typeof BrandApplicationsRoute
  '/color': typeof BrandColorRoute
  '/data-viz': typeof BrandDataVizRoute
  '/iconography': typeof BrandIconographyRoute
  '/imagery': typeof BrandImageryRoute
  '/logo': typeof BrandLogoRoute
  '/position': typeof BrandPositionRoute
  '/proof': typeof BrandProofRoute
  '/resources': typeof BrandResourcesRoute
  '/tools': typeof BrandToolsRoute
  '/typography': typeof BrandTypographyRoute
  '/voice': typeof BrandVoiceRoute
  '/': typeof BrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_brand': typeof BrandRouteWithChildren
  '/about': typeof AboutRoute
  '/logo-assets': typeof LogoAssetsRoute
  '/newsletter': typeof NewsletterRoute
  '/positioning': typeof PositioningRoute
  '/principles': typeof PrinciplesRoute
  '/review': typeof ReviewRoute
  '/sketches': typeof SketchesRoute
  '/social-media': typeof SocialMediaRoute
  '/visual-system': typeof VisualSystemRoute
  '/_brand/applications': typeof BrandApplicationsRoute
  '/_brand/color': typeof BrandColorRoute
  '/_brand/data-viz': typeof BrandDataVizRoute
  '/_brand/iconography': typeof BrandIconographyRoute
  '/_brand/imagery': typeof BrandImageryRoute
  '/_brand/logo': typeof BrandLogoRoute
  '/_brand/position': typeof BrandPositionRoute
  '/_brand/proof': typeof BrandProofRoute
  '/_brand/resources': typeof BrandResourcesRoute
  '/_brand/tools': typeof BrandToolsRoute
  '/_brand/typography': typeof BrandTypographyRoute
  '/_brand/voice': typeof BrandVoiceRoute
  '/_brand/': typeof BrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/logo-assets'
    | '/newsletter'
    | '/positioning'
    | '/principles'
    | '/review'
    | '/sketches'
    | '/social-media'
    | '/visual-system'
    | '/applications'
    | '/color'
    | '/data-viz'
    | '/iconography'
    | '/imagery'
    | '/logo'
    | '/position'
    | '/proof'
    | '/resources'
    | '/tools'
    | '/typography'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/logo-assets'
    | '/newsletter'
    | '/positioning'
    | '/principles'
    | '/review'
    | '/sketches'
    | '/social-media'
    | '/visual-system'
    | '/applications'
    | '/color'
    | '/data-viz'
    | '/iconography'
    | '/imagery'
    | '/logo'
    | '/position'
    | '/proof'
    | '/resources'
    | '/tools'
    | '/typography'
    | '/voice'
    | '/'
  id:
    | '__root__'
    | '/_brand'
    | '/about'
    | '/logo-assets'
    | '/newsletter'
    | '/positioning'
    | '/principles'
    | '/review'
    | '/sketches'
    | '/social-media'
    | '/visual-system'
    | '/_brand/applications'
    | '/_brand/color'
    | '/_brand/data-viz'
    | '/_brand/iconography'
    | '/_brand/imagery'
    | '/_brand/logo'
    | '/_brand/position'
    | '/_brand/proof'
    | '/_brand/resources'
    | '/_brand/tools'
    | '/_brand/typography'
    | '/_brand/voice'
    | '/_brand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BrandRoute: typeof BrandRouteWithChildren
  AboutRoute: typeof AboutRoute
  LogoAssetsRoute: typeof LogoAssetsRoute
  NewsletterRoute: typeof NewsletterRoute
  PositioningRoute: typeof PositioningRoute
  PrinciplesRoute: typeof PrinciplesRoute
  ReviewRoute: typeof ReviewRoute
  SketchesRoute: typeof SketchesRoute
  SocialMediaRoute: typeof SocialMediaRoute
  VisualSystemRoute: typeof VisualSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_brand': {
      id: '/_brand'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-assets': {
      id: '/logo-assets'
      path: '/logo-assets'
      fullPath: '/logo-assets'
      preLoaderRoute: typeof LogoAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positioning': {
      id: '/positioning'
      path: '/positioning'
      fullPath: '/positioning'
      preLoaderRoute: typeof PositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketches': {
      id: '/sketches'
      path: '/sketches'
      fullPath: '/sketches'
      preLoaderRoute: typeof SketchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-system': {
      id: '/visual-system'
      path: '/visual-system'
      fullPath: '/visual-system'
      preLoaderRoute: typeof VisualSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand/': {
      id: '/_brand/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/applications': {
      id: '/_brand/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof BrandApplicationsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/color': {
      id: '/_brand/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof BrandColorRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/data-viz': {
      id: '/_brand/data-viz'
      path: '/data-viz'
      fullPath: '/data-viz'
      preLoaderRoute: typeof BrandDataVizRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/iconography': {
      id: '/_brand/iconography'
      path: '/iconography'
      fullPath: '/iconography'
      preLoaderRoute: typeof BrandIconographyRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/imagery': {
      id: '/_brand/imagery'
      path: '/imagery'
      fullPath: '/imagery'
      preLoaderRoute: typeof BrandImageryRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/logo': {
      id: '/_brand/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof BrandLogoRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/position': {
      id: '/_brand/position'
      path: '/position'
      fullPath: '/position'
      preLoaderRoute: typeof BrandPositionRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/proof': {
      id: '/_brand/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof BrandProofRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/resources': {
      id: '/_brand/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof BrandResourcesRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/tools': {
      id: '/_brand/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof BrandToolsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/typography': {
      id: '/_brand/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof BrandTypographyRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/voice': {
      id: '/_brand/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof BrandVoiceRouteImport
      parentRoute: typeof BrandRoute
    }
  }
}

interface BrandRouteChildren {
  BrandApplicationsRoute: typeof BrandApplicationsRoute
  BrandColorRoute: typeof BrandColorRoute
  BrandDataVizRoute: typeof BrandDataVizRoute
  BrandIconographyRoute: typeof BrandIconographyRoute
  BrandImageryRoute: typeof BrandImageryRoute
  BrandLogoRoute: typeof BrandLogoRoute
  BrandPositionRoute: typeof BrandPositionRoute
  BrandProofRoute: typeof BrandProofRoute
  BrandResourcesRoute: typeof BrandResourcesRoute
  BrandToolsRoute: typeof BrandToolsRoute
  BrandTypographyRoute: typeof BrandTypographyRoute
  BrandVoiceRoute: typeof BrandVoiceRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandApplicationsRoute: BrandApplicationsRoute,
  BrandColorRoute: BrandColorRoute,
  BrandDataVizRoute: BrandDataVizRoute,
  BrandIconographyRoute: BrandIconographyRoute,
  BrandImageryRoute: BrandImageryRoute,
  BrandLogoRoute: BrandLogoRoute,
  BrandPositionRoute: BrandPositionRoute,
  BrandProofRoute: BrandProofRoute,
  BrandResourcesRoute: BrandResourcesRoute,
  BrandToolsRoute: BrandToolsRoute,
  BrandTypographyRoute: BrandTypographyRoute,
  BrandVoiceRoute: BrandVoiceRoute,
  BrandIndexRoute: BrandIndexRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BrandRoute: BrandRouteWithChildren,
  AboutRoute: AboutRoute,
  LogoAssetsRoute: LogoAssetsRoute,
  NewsletterRoute: NewsletterRoute,
  PositioningRoute: PositioningRoute,
  PrinciplesRoute: PrinciplesRoute,
  ReviewRoute: ReviewRoute,
  SketchesRoute: SketchesRoute,
  SocialMediaRoute: SocialMediaRoute,
  VisualSystemRoute: VisualSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
